version: '3.3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.16
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"

  client:
    environment:
      - CLIENT_JAEGERHOST=jaeger
    build:
      context: .
      dockerfile: client/Dockerfile
